docs/auparse_interpret_field.3
In debian, lintian is complaining about the auparse_interpret_field
manpage with the following warning:
W: libauparse-dev: manpage-has-errors-from-man usr/share/man/man3/auparse_interpret_field.3.gz 41: warning [p 1, 9.2i]: can't break line
See: https://lintian.debian.org/tags/manpage-has-errors-from-man.html
=> Fix line breakage in auparse_interpret_field manpage

src/aureport-output.c
I started to backport https://github.com/linux-audit/audit-userspace/commit/25097d64344828a80acf681da5c1dacc4ea3c069 and was confused by an old, incorrect code comment. This trivial PR updates the comment to match the code change.
=> aureport: Adjust code comment for printing RPT_LOGIN reports

bindings/python/auparse_python.c
Some new record types have been added recently, but the Python bindings haven't kept up.
=> expose all members of ausparse_type_t to Python

src/auditd-event.c
Previously, the check was for (max_log_size_action == SZ_ROTATE && config->num_logs < 2) only. However, the rotate_logs() function can be invoked using a USR1 signal independently on the action defined.
When num_logs = 0 and max_log_file_action = IGNORE (other than ROTATE) the auditd busy-looped due to integer underrun in the for loop.
With num_logs = 1 and max_log_file_action = IGNORE, the oldname was uninitialized.
This commit exits the rotate_logs() function when log rotation is disabled and adds a LOG_NOTICE.
=> Do not rotate logs when num_logs < 2.

lib/libaudit.c
Related kernel GH issue: https://github.com/linux-audit/audit-kernel/issues/53
=> Add support for executable name not equal operator

audisp/plugins/remote/audisp-remote.c
Looks like etok.value should be free'd here
=> Fix memory leak in audisp-remote

auparse/test/Makefile.am
Overwriting check: created a race condition that can cause
parallel builds to fail due to twomake processes in parallel
building the same files.
=> auparse/test/: Don't build test programs twice in parallel

bindings/swig/src/auditswig.i
auditswig.i hard codes the path to stdint.h. That will fail to work with
non-glibc libcs and after moving glibc's headers (#798955). The path is
hard coded, because swig's %include does not search the standard header
search path. Rather than using %include here, we can use #include,
because stdint.h does not declare any functions. Thus swig entirely
ignores stdint.h and leaves the search to the C compiler.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909967
=> bindings/swig/src/auditswig.i: Do not hardcode the path of stdint.h

bindings/swig/python3/Makefile.am
`am__py_compile` was previously defined as
```make
am__py_compile = PYTHON=$(PYTHON3) $(SHELL) $(py_compile)
```
As the original definition of `am__py_compile` produced by automake is
```make
am__py_compile = PYTHON=$(PYTHON) $(SHELL) $(py_compile)
```
it should be sufficient to just
```make
PYTHON = $(PYTHON3)
```
in `Makefile.am`
=> Remove `am__py_compile` redefinition

init.d/auditd.service
In recent versions systemd starts complaining:
/usr/lib/systemd/system/auditd.service:12: PIDFile= references path below
legacy directory /var/run/, updating /var/run/auditd.pid → /run/auditd.pid;
please update the unit file accordingly.
So let's just update the paths.
=> Update all paths /var/run -> /run

docs/auditd.conf.5
Specifically, clarify that the audit daemon triggers ```space_left_action``` when the free space in the filesystem containing ```log_file``` drops below the value specified by ```space_left``` (either as an absolute value, or as a percentage).
The previous description did not make it clear exactly how the ```space_left``` parameter was interpreted, leading to confusion.
=> Clarify the documentation for the space_left parameter.

configure.ac
Newer distributions, esp. Fedora 31+, changed the unversioned symlink to the Python interpreter from Python2 to Python3.
We are now facing problems, because the `AM_PATH_PYTHON` macro tries the unversioned python symlink first to find the Python2 interpreter, thus we need to find and specify the full path to the system's Python2 interpreter before calling this macro.
This approach is less intrusive than #102.
There is also a small syntax fix for some warning included in a separate commit.
=> Python2 detection.

docs/audit_set_pid.3
The `audit_set_pid` man page is missing the third parameter. I've added it, and briefly extended the usage.
=> audit_set_pid: add wmode to man page

bindings/python/auparse_python.c, lib/libaudit.c, lib/libaudit.h, src/auditctl.c, src/autrace.c
* Throw a const into auparse_python and clean up some spacing
* Add audit_rule_init_data() and audit_rule_data_create() to match audit_rule_data_free(), motivated by transient EINVAL from audit_add_rule (I wasn't initializing buflen to 0)
* Use audit_rule_*_data() in auditctl and autrace
=> Add audit_rule_*_data, small cleanups

src/auditd-config.c
NixOS' readonly state system creates binaries with `0500` and directories
with `0555` permissions. To be able to run `audit` on this system we
have to add those permissions to the check, too.
=> Allow 0555 and 0550 permissions of executable

docs/audit.rules.7
Fix wrong syntax in an example.
=> audit.rules.7: fix filter syntax

lib/libaudit.c, lib/libaudit.h, lib/netlink.c, src/auditctl-listing.c, src/auditctl.c
Untangle AUDIT_FEATURE_VERSION and AUDIT_FEATURE_BITMAP since they have nothing
to do with each other.
AUDIT_FEATURE_VERSION is a method to enable and lock certain audit features in
the kernel.  Threre are currently only two.
AUDIT_FEATURE_BITMAP is a method to determine what features exist in the kernel
implementation of audit.  There are currently seven.
fixes: a22f13a548d2f26b3fb05b31599f5b12f56d3d07 ("Fix compile time feature detection in auditctl")
fixes: 74327320a25b2d889708002908d6a051b4dfea51 ("Fix compile time feature detection in auditctl")
fixes: f588248775b4f8180b846bbc1681bc54e07871ed ("Better detect struct audit_status existence")
fixes: bed754a651f47f5a83bbf565609e4936b0270269 ("Fix building on old kernels")
Please see issue page …
=> fix FEATURE_VERSION vs FEATURE_BITMAP

audisp/plugins/remote/Makefile.am, audisp/plugins/syslog/Makefile.am, auparse/Makefile.am, auparse/test/Makefile.am, common/Makefile.am, lib/Makefile.am
This makes sure that the functions compiled into libaucommon
(audit_strsplit_r,...) ends up in the libaudit/libauparse static library
Fixes: #146
=> Turn libaucommon into a libtool convenience library

configure.ac
Without these changes libaudit used to have a libpthread dependency that caused errors in linux-pam.
=> Fix configure.ac to not add libpthread to LIBS

audisp/Makefile.am, audisp/plugins/ids/Makefile.am, audisp/plugins/remote/Makefile.am, audisp/plugins/statsd/Makefile.am, audisp/plugins/syslog/Makefile.am, audisp/plugins/zos-remote/Makefile.am, src/Makefile.am, src/libev/Makefile.am, tools/aulast/Makefile.am, tools/aulastlog/Makefile.am, tools/ausyscall/Makefile.am, tools/auvirt/Makefile.am
When building against slibtool (https://dev.midipix.org/cross/slibtool) it fails.
```
rdlibtool --tag=CC --mode=link gcc -fPIE -DPIE -g -D_GNU_SOURCE -Wundef -g -O2 -pie -Wl,-z,relro -Wl,-z,now -o audisp-syslog audisp_syslog-audisp-syslog.o -lcap-ng -L../../../common -laucommon -L../../../auparse -lauparse
rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/audit-userspace/audisp/plugins/syslog"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 45, .st_ino = 41159}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(AT_FDCWD,"../",O_DIRECTORY,0) = 3.
rdlibtool: lconf: fstat(3,...) = 0 {.st_dev = 45, .st_ino = 41100}.
rdlibtool: lconf: openat(3,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: …
```
=> build: Link with libtool archives instead.

lib/netlink.c
When an error occurs in fcntl(), strerror(errno) is called after close().
If an error occurs in close(), it will overwrite the errno of fcntl().
Therefore, the timing of close() is changed after strerror(errno).
=> Fix the closing timing of audit_fd

docs/audit_get_reply.3
audit_get_reply.3 states that -1 is returned on error, but in implementation it returns -errno.
Fix the return value of audit_get_reply.3 to -errno according to the implementation.
=> Fix the return value of audit_get_reply.3 to -errno

docs/set_aumessage_mode.3
So far, the man-page of set_message_mode(3) has existed, but the man-page of set_aumessage_mode(3) has not.
set_message_mode does not exist in libaudit.
Therefore, the man-page of set_message_mode(3) was deleted and the man-page of set_aumessage_mode(3) was added.
=> Add man-page set_aumessage_mode(3)

audisp/plugins/zos-remote/audispd-zos-remote.conf, docs/zos-remote.conf.5
All audispd config files have been moved to "/etc/audit" in the commit a5f7baf0917a60cacbd237ba1f1512db63445031.
The file zos-remote.conf is still configured under /etc/audisp in audispd-zos-remote.conf.
=> Fix the default location for zos-remote.conf

docs/audit_log_user_avc_message.3, docs/auparse_get_milli.3
There is a man-page that references to its own man-page.
Fixed not to refer to own man-page.
=> Fix not to list own man-page in "SEE ALSO"

init.d/auditd.service
Use `Restart=on-failure` to automatically restart `auditd`. Do not restart for intentional exits. See EXIT CODES section in auditd(8).
See:
- https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=
- https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartPreventExitStatus=
Fixes: https://github.com/linux-audit/audit-userspace/issues/211
=> auditd.service: Restart 'on-failure', ignoring some exit codes

auparse/interpret.c
When defining dest = rpath + 1, we end up having the first char of
`dest' as NULL -- since `rpath' points to `working', which is a static
buffer.
With the first char as NULL, path_norm() ends up producing an empty string.
This commit fixes the issue reported in this [1] mailing list post.
[1] https://listman.redhat.com/archives/linux-audit/2022-February/018844.html
=> auparse: fix off-by-one issue in path_norm()

audisp/plugins/remote/audisp-remote.c
Bug description:
If auditd.conf has disk_low_action=suspend and the partition where the
log is triggers the disk_low_action, audisp-remote will hang in
infinite loop.
Reproduce:
- enable audisp-remote plugin
- set disk_low_action=suspend in auditd.conf
- fill partition where /var/log/audit is
- wait for disk_low_action to kick in
Results:
audisp-remote keeps running with 100% CPU usage, no further actions from it
Expected results:
audisp-remote is suspended
Fixes: 10dde069d1ac ("Dont look for stop on exit while draining the queue")
Signed-off-by: Enzo Matsumiya <ematsumiya@suse.de>
=> audisp-remote: fix hang with disk_low_action=suspend

bindings/python/auparse_python.c
Fixes: 9976d2c ("Fix the other instance of PyTypeObject which uses .tp_compare which is now deprecated")
Build error was:
```
DEBUG: ../../../bindings/python/auparse_python.c:231:6: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_compare'<...>
DEBUG:      .tp_compare = AuEvent_compare,
DEBUG:       ^~~~~~~~~~
```
=> Fix building with Python 3.5

docs/auditctl.8
This is a repost of #292 :
Following up the discussion at #279 , I think the documentation can be improved in order to remove any ambiguity. The file read in by the -R option contains commands instead of rules.
For example, in 10-base-config.rules, there is a line -b 8192 -- it is a command, not a rule.
I've also added an example that explicitly mentions the need to execute the '-D' command in order to clear any preexisting rules.
The above is based on my understanding of how auditctl operates, please correct me if I'm wrong.
=> Explain -R more precisely and give an example

src/auditctl.c
In case ```auditctl``` is executed with args that do not start with the '-' character, no information is displayed to the user. It can be reproduced by e.g.: ```auditctl something non existing params```.
In case rules are loaded from a file, this was already handled correctly. See https://github.com/linux-audit/audit-userspace/blob/master/src/auditctl.c#L1401
=> Provide meaningful error message when executing auditctl with wrong params

auparse/auparse.h
__attribute_malloc__ is not available on musl
Fixes
| ../../git/auparse/auparse.h:54:2: error: expected function body after function declarator
|         __attribute_malloc__ __attr_dealloc (auparse_destroy, 1);
|         ^
Downloaded from https://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-security/audit/audit/0001-Replace-__attribute_malloc__-with-__attribute__-__ma.patch
=> Replace __attribute_malloc__ with __attribute__((__malloc__))

src/auditd-reconfig.c
auditd-reconfig.c: In function 'start_config_manager': auditd-reconfig.c:63:42: warning: the comparison always evaluates to false because pthread_create always returns non-negative values
=> Fix the error found by clang-tidy

auparse/interpret.c, src/ausearch-parse.c
According to `man 7 unix`, an unnamed (or anonymous) AF_UNIX socket will have the following properties:
- its address length will be sizeof(sa_family_t)
- sun_family is AF_LOCAL/AF_UNIX (0x1) (obviously, but see below)
- sun_path must not be inspected (empirical evidence suggests sun_path[0] is 0 most of the time though)
Thus, the hex representation of such sockaddr_un is '0100'.  Which is observable as "saddr=0100" in SOCKADDR messages, or "len too short" when interpret flag '-i' is passed.
Example error messages:
```
Executable Summary Report
=================================
total  file
=================================
sun_path len too short
sun_path len too short
...
sun_path len too short
sun_path len too short
9426  /usr/bin/grep
7070  /usr/sbin/nmbd
2461  /usr/bin/rm
...
... …
```
=> Check for AF_UNIX unnamed sockets

audisp/plugins/af_unix/af_unix.conf
For `path = builtin_af_unix`, fixes:
```
auditd[981]: Option builtin_af_unix line 10 is obsolete - using /sbin/audisp-af_unix
```
See: https://github.com/linux-audit/audit-userspace/blob/2cf5c2e0f72e5977b1fcbb136d084a041d06e4fd/audisp/audispd-pconfig.c#L397
For `type = builtin`, fixes:
```
auditd[981]: Option builtin line 11 is obsolete - update it
```
See: https://github.com/linux-audit/audit-userspace/blob/2cf5c2e0f72e5977b1fcbb136d084a041d06e4fd/audisp/audispd-pconfig.c#L432
=> audisp/af_unix.conf: Update default config values

docs/ausearch.8
This patch adds an example to ausearch man page for checking denials today, this is a common use for people visiting the man page.
=> Update ausearch.8 to include common example

audit.spec
I found that the af_unix.conf does not need to exist in the main package. And the file is already in the audispd-plugins package.
=> delete af_unix.conf in audit package

src/ausearch.c
When processing a file using ```ausearch -if file_name``` as non-root user, the following is displayed:
```
$ ausearch -if ./test
Error opening config file (Permission denied)
NOTE - using built-in logs: /var/log/audit/audit.log
<no matches>
```
With patch applied:
```
Error opening config file (Permission denied)
NOTE - using built-in end_of_event_timeout: 2
<no matches>
```
The behavior is not changed, but correct information about configuration options are displayed to the user.
In case you are not able to view the config file, ```end_of_event_timeout``` can't be queried.
=> ausearch: do not use built-in logs when --input is specified

ChangeLog, README.md, audisp/plugins/ids/README.md, audisp/plugins/ids/timer-services.c, audisp/plugins/remote/audisp-remote.8, audisp/plugins/remote/audisp-remote.c, audisp/plugins/statsd/audisp-statsd.c, audisp/plugins/zos-remote/zos-remote-ldap.c, audisp/plugins/zos-remote/zos-remote-plugin.c, auparse/data_buf.c, auparse/ellist.c, auparse/expression.c, auparse/expression.h, auparse/internal.h, auparse/interpret.c, auparse/test/auparselol_test.c, docs/audispd-zos-remote.8, docs/auparse_find_field.3, init.d/auditd.service, init.d/augenrules, lib/libaudit.c, src/auditctl.c, src/auditd-event.c, src/auditd-listen.c, src/ausearch-parse.c, src/ausearch.c, tools/ausyscall/ausyscall.8
Found by codespell(1) and typos[1] (embedded libev source excluded).
[1]: https://github.com/crate-ci/typos
=> Fix misspellings

lib/audit_logging.c, lib/libaudit.c
Allow the compiler to verify the format string matches the supplied arguments.
=> lib: rework format strings

lib/libaudit.c, lib/libaudit.h
Also /proc/<pid> should be a directory.
=> lib: declare read-only parameters of audit_format_signal_info() const

src/aureport-options.c, src/ausearch-options.c
This fixes type-conflicting definitions and declarations.
Reported by CBMC's goto-cc compiler, which performs type-aware linking.
I should add that I am somewhat unsure about a change introduced in 1a0bfcc9a449: it parsed negative session ids with base `0`, which would suggest that inputs must be base 16 (but only in the negative case)?!
=> Make session id consistently signed

src/ausearch-lol.c, src/ausearch-lol.h, src/ausearch.c
Ausearch only marks events complete (see --checkpoint of ausearch command) when adding a new event from the log source. This means that if the last event in a log source is complete, then it will not be emitted when checkpointing.
This PR addresses this issue.
=> Issue343: Fix checkpoint issue to ensure all complete events are gained

lib/netlink.c
Signed integer overflow is undefined, allowing compilers to optimize the condition `++sequence < 0` away.
=> lib: avoid UB on sequence wrap-around

audisp/audispd-pconfig.c, audisp/audispd-pconfig.h, audisp/audispd.c
Every plugin configuration line comprises a key = value pair, optionally followed by an additional option at the line's end. Previously, if the value consisted of multiple words, an error would occur. This commit addresses the issue, allowing for the specification of multiple space-separated arguments in a plugin configuration. For instance, the audisp-syslog plugin can handle 3 arguments, but we were not able to pass all 3 at a single time due to this limitation.
```
args = LOG_NOTICE LOG_LOCAL0 interpret
```
=> audispd: Variable amount of arguments

auparse/auparse.c, auparse/auparse.h, auparse/test/auparse_test.c, docs/Makefile.am, docs/ausearch_add_expression.3, docs/ausearch_add_interpreted_item.3, docs/ausearch_add_item.3, docs/ausearch_add_regex.3, docs/ausearch_add_timestamp_item.3, docs/ausearch_add_timestamp_item_ex.3, docs/ausearch_cur_event.3, docs/ausearch_set_stop.3
The `ausearch_cur_event` function will scan the input source and evaluate whether any record in the current event contains the data being searched for.
The first part of `ausearch_cur_event` and `ausearch_next_event` are identical, so it can be moved to a separate function to remove duplicate code if needed.
This will help us to progress with https://github.com/linux-audit/audit-userspace/pull/352
=> libaudit: add ausearch_cur_event

.gitignore, audisp/plugins/Makefile.am, audisp/plugins/filter/Makefile.am, audisp/plugins/filter/audisp-filter.8, audisp/plugins/filter/audisp-filter.c, audisp/plugins/filter/audisp-filter.conf, audisp/plugins/filter/filter-syslog.conf, audisp/plugins/filter/filter.conf, configure.ac
Audit plugins are components used in the Linux audit system to extend its functionality and customize the way audit events are processed and handled on userspace level. One common feature that all plugins lack is the ability to filter out specific events. The goal of this PR is to introduce a new plugin, capable of filtering out specific audit events based on the configuration passed to. Furthermore, it's able to forward remaining logs to the configured plugin, operating in both allowlisting and blocklisting modes.
The `audisp-filter` program is accompanied by an associated config file containing `ausearch-expression(5)` s. Each line represents an  expression that can be either a simple rule or a very complex expression. These rules are grouped together using the OR operator to form one …
=> audisp-filter: new plugin that provides audit event filtering capability

src/ausearch-parse.c
I recently sent a similar PR, but missed two more potential dereferences of null pointers. 
In general, there are many points in the parse_user() function where dynamic memory allocation occurs. But the subsequent pointer dereference occurs only in one place. I do not know how critical this is, so I did not add many checks, I made only one obvious one.
=> avoiding of NULL pointers dereference

README.md
Auditd does not depend on `systemd` for building and running. It only depends on `systemd` if systemd service files are used to start `auditd`. But `auditd` can be started by other init systems e.g. OpenRC as well. As done in Alpine Linux (https://git.alpinelinux.org/aports/tree/main/audit/auditd.initd)
Therefore stating `systemd` as runtime dependency is misleading.
=> Remove systemd as runtime dependecy

configure.ac
I came across the following warning when inspecting the build output.  There are many unnecessary warnings regarding subdir-objects option. Details: https://www.gnu.org/software/automake/manual/html_node/List-of-Automake-options.html#index-Options_002c-subdir_002dobjects 
```
auparse/Makefile.am:92: warning: source file '../lib/gen_tables.c' is in a subdirectory,
auparse/Makefile.am:92: but option 'subdir-objects' is disabled
automake-1.16: warning: possible forward-incompatibility.
automake-1.16: At least one source file is in a subdirectory, but the 'subdir-objects'
automake-1.16: automake option hasn't been enabled.  For now, the corresponding output
automake-1.16: object file(s) will be placed in the top-level directory.  However, this
automake-1.16: behavior may change in a future …
```
=> Add subdir-objects option to automake

docs/auditd.8
Backport the patch to 3.1 as well, source: https://github.com/linux-audit/audit-userspace/pull/387
=> [audit-3.1-maint] Correct the auditd manpage regarding stop rules

auparse/auparse.c, src/ausearch-lol.c
Looking at
https://www.gnu.org/software/libc/manual/html_node/Truncating-Strings.html , `strndupa` is implemented as a macro. It uses `malloca`, which allocates space in the stack frame of the caller. The temporary space is automatically freed when the function that called alloca returns.
Fixes #381
=> Custom strndupa: Convert it to a macro instead of a function

audit.spec
Fixes: 7169631bef7c ("Update the spec file to be more correct")
=> audit.spec: remove unsupported '--enable-systemd'

init.d/auditd.service.in
Replaced `Requires=audit-rules.service` with `Wants=audit-rules.service` in auditd.service to align with behavior from audit v4.0 and earlier. This modification ensures that if `audit-rules.service` fails to load rules into the kernel, `auditd` will not be forced to exit. This change preserves backward compatibility and prevents potential disruptions caused by issues in rule loading.
=> Change dependency from Requires to Wants for audit-rules.service

common/common.c
While consolidating the end of event function to a function, in
commit ccd4bdb, the behavior changed as some messages -- such as
AUDIT_USER messages -- were not considered anymore.
Example:
1) Before the change:
```
ts1="$(date +%T)"
touch test1.log
auditctl -m test1
ausearch -ts "${ts1}"  --checkpoint chk1
----
time->Tue Sep 10 14:45:20 2024
type=USER msg=audit(1725993920.729:2968): pid=63311 uid=0 auid=0 ses=4 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='text=test1 exe="/usr/sbin/auditctl" hostname=hostname-here addr=? terminal=pts/0 res=success'
```
2) After the change (current behavior):
```
ts2="$(date +%T)"
touch test2.log
auditctl -m test2
ausearch -ts "${ts2}" --checkpoint chk2
<no matches>
```
This commit gets the previous behavior back.
=> Fix checkpoint issue regarding AUDIT_USER end of event detection

audisp/audispd.c, docs/auditd-plugins.5
While the naming format for plugin configuration files is documented in the auditd-plugins(5) man page, it may appear counterintuitive and deviates from the common naming conventions followed by other widely-used components (e.g., systemd, httpd, SELinux, dracut, and others).
This patch also addresses the handling of non-regular files.
With the patch applied, plugin configurations matching the following pattern would be skipped:
- not a regular file
- hidden file
- backup file
- file without .conf suffix
=> Skip plugin configs that do not have .conf suffix

audisp/plugins/filter/audisp-filter.8, audisp/plugins/filter/audisp-filter.c
1. Fix the behavior of forwarding events in the filtering plugin, when looping through records.
2. Minor doc bugfix
=> audisp-filter: Traverse events correctly when forwarding

src/ausearch-checkpt.c
This code uplifts the checkpointing code's use of ino_t and dev_t to treat them as 64 bit quantities.
The code addresses https://github.com/linux-audit/audit-userspace/issues/404
=> Modify ausearch checkpoint code to address audit-userspace issue 404

auparse/interpret.c
When a path contains ".." character, it requires normalization to resolve these. However, certain cases caused unexpected behavior, resulting in segmentation faults due to invalid memory access.
In `path_norm`, when encountering `".."`, the function attempts to backtrack to the previous `"/"` character. This approach failed when the leading `"/"` characters were removed earlier in the function, causing out-of-bounds memory access.
This fix ensures proper handling of ".." by adjusting the backtracking logic to account for removed leading slashes, preventing segmentation faults.
Steps to reproduce the original issue: Pass `"/root/../some-path"` into `path_norm` as an argument.
=> Path normalization: fix segmentation fault for ".." handling

auparse/auparse.c, src/ausearch-checkpt.c, src/ausearch.c
Need to set the format specifier of %lld for some prints of an event's seconds value as time_t is now int64_t. In case of back porting to a 32 bit time_t, the output is caste to (long long int) when printing.
=> Correct printf format specifier as per issue 406

auparse/normalize.c
In some cases, ausearch was not correctly showing the new name of a renamed file when searching for audit events. If the target file didn’t exist prior to the rename, ausearch was unable to parse the new file name. This occurred because  ausearch attempted to retrieve this information from the 7th record, which is absent when the target file does not exist.
Before patch:
```
At 08:37:22 10/18/2024 alakatos successfully renamed /home/alakatos/github/audit-userspace/test/r-r using /home/alakatos/github/audit-userspace/test/main
```
After patch:
```
At 08:37:22 10/18/2024 alakatos successfully renamed /home/alakatos/github/audit-userspace/test/r-r to /home/alakatos/github/audit-userspace/test/r-r.renamed using /home/alakatos/github/audit-userspace/test/main
```
The same goes for the csv …
=> ausearch format: Fix display of renamed file

init.d/Makefile.am, init.d/audit-tmpfiles.conf
On image based systems for many years the idea has been to have the operating system content live in `/usr` as much as possible, and synthesize data outside there via external tools. For `/var` content, systemd-tmpfiles is a go to choice for situations like this.
For more information see
xref https://gitlab.com/fedora/bootc/tracker/-/issues/50
https://issues.redhat.com/browse/RHEL-70633
=> Add audit-tmpfiles.conf to ensure /var/lib/audit exists

auparse/interpret.c
=> interpret: allow hex digits when interpreting tty data

src/ausearch-parse.c
In `parse_daemon1()`, we may have the uid= field appear both before and after pid=, which may cause our parsing of it to fail, as we may have skipped past it. For uid=, let us search from the beginning.
Example for this case:
`type=DAEMON_END msg=audit(1709723032.140:753): op=terminate auid=0 uid=0 ses=8 pid=107086 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 res=success`
`ausearch -if sample.log -a 753 -m DAEMON_END  -ui 0 --session 8 -p 107086 --success yes`
=> ausearch-parse: fix parsing for success/uid in parse_daemon1()

audisp/Makefile.am, audisp/plugins/remote/audisp-remote.c, audisp/queue.c, common/common.c, common/common.h, src/auditd-event.c
Audit may initiate runlevel changes in several scenarios, such as when available disk space for audit logs becomes critically low. In these situations, audit can halt the system during boot, but without clear evidence indicating that audit was responsible for the shutdown. With the patch applied, audit will write to `/dev/console` when doing runlevel changes.
This comes in handy during boot, so sysadmins can track down the root cause of the shutdown much faster.
=> Log runlevel changes to console (during boot)

audisp/plugins/af_unix/Makefile.am, audisp/plugins/af_unix/audisp-af_unix.c
Since the plugin got separated into a standalone util, the the dispatcher and the plugin were not synchronized in terms of how much data they process. audisp-af_unix read less data than the dispatcher, resulting in data misalignment.
Original bug description: https://bugzilla.redhat.com/show_bug.cgi?id=2273726
There are a few approaches how this could be handled:
1. The af_unix plugin must accept "binary" as input. The output format will be determined by a new parameter: if it's set to binary, the plugin will simply forward the header and data. If it's set to string, the data will be parsed using the code from audispd.c. This is the approach implemented in the current PR.
2. The input format could be either string or binary, with the output format matching the chosen input format. …
=> propagate format mode to the audisp-af_unix plugin

audisp/plugins/af_unix/audisp-af_unix.c, audisp/plugins/filter/audisp-filter.c
Fix a few warnings/issues detected by covscan:
```
Error: RESOURCE_LEAK
audit-4.0.3/audisp/plugins/af_unix/audisp-af_unix.c:248:6: alloc_arg: "event_to_string" allocates memory that is stored into "str".
audit-4.0.3/audisp/plugins/af_unix/audisp-af_unix.c:254:7: noescape: Resource "str" is not freed or pointed-to in "write".
audit-4.0.3/audisp/plugins/af_unix/audisp-af_unix.c:256:5: leaked_storage: Variable "str" going out of scope leaks the storage it points to.
```
```
Error: STRING_SIZE
audit-4.0.3/audisp/plugins/filter/audisp-filter.c:390:32: string_size_argv: "argv" contains strings with unknown size.
audit-4.0.3/audisp/plugins/filter/audisp-filter.c:428:3: string_size: Passing string "argv[0]" of unknown size to "syslog".
```
```
Error: STRING_SIZE …
```
=> Fix a few covscan findings introduced recently

src/auditd-event.c, src/auditd.c
Lowering the priority of normal progress messages makes it easier for users to notice the messages they might need to do something about.
=> Change several log levels from NOTICE to INFO

lib/libaudit.c
Filter syscalls to ensure compatibility with architecture-specific availability
Added logic to filter syscalls during rule creation to exclude unsupported syscalls based on the target architecture. Falls back to the original syscall list if filtering fails.
Reproducer on aarch64:
```
30-stig.rules:-a always,exit -F arch=b64 -F path=/etc/group -F perm=wa -F key=identity
```
The above translates to a list of monitored syscalls, including `rename`, which is hardcoded and added to audit rules even if unavailable on `aarch64`. This patch filters out such syscalls during rule creation.
=> permtab fix: filter unsupported syscalls based on architecture

docs/auditd.conf.5, src/auditd-config.c, src/auditd-config.h, src/auditd-event.c
The previously available HALT option, which would cause the audit daemon to shut down the computer system, has been deprecated and should no longer be used. It was determined that halting the system at this stage could lead to unintended consequences and is considered a bad action if selected.
=> auditd config: remove HALT option from space_left_action

audisp/audispd-pconfig.c
While trying to use `auditd` with https://github.com/threathunters-io/laurel on NixOS I was getting an error:
/nix/store/9q60x1fc4yq5av5c5g5h2ccmkprb9h4z-laurel-0.6.4-for-auditd/bin/laurel permissions should be 0750
This is:
- on one side the issues is specific to Nix, where no `/nix/store` file has write access at all (binaries are `0555`)
- on the other side I don't expect `auditd`  to write to that binary file, therefore it should not check for write permissions at all
=> audispd-pconfig.c: don't check unnecessary write permissions

audit.spec, docs/Makefile.am, docs/auditd.conf.5, docs/auditd.cron.5, init.d/auditd.cron
Many users frequently ask whether time-based log rotation is possible in `auditd` and how to configure it. The purpose of this change is to provide a general guide on setting up time-based log rotation. Output is a new man page named auditd.cron.
My intention is not to set a strict guideline on how to configure it or what exact values to set in the main config. Feedback is appreciated. Will do some testing later.
=> auditd.cron.5: Describe time-based log rotation setup

lib/audit_logging.c
If the hostname or addr fields are omitted, audit will attempt to determine them automatically. The addr can be resolved from the hostname, while the hostname can be inferred if an active TTY is present. However, hostname resolution must occur before address resolution when the hostname is also needed for address deduction.
record before:
```
type=USER_ACCT msg=audit(02/24/2025 08:27:39.767:144) : pid=1369 uid=root auid=root ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:accounting grantors=pam_succeed_if acct=root
exe=/usr/bin/su hostname=? addr=? terminal=/dev/pts/0 res=success' 
```
record after:
```
type=USER_ACCT msg=audit(02/24/2025 08:48:43.213:236) : pid=20034 uid=root auid=root ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 …
```
=> logging: retrieve addr and hostname fields even if not explicitly specified

lib/libaudit.c, src/auditctl.c
The first two are due to the nature of realloc. It's safer to use a temporary var, so rule can still hold the old ptr in case realloc fails.
The third and fourth are minor issues that crept in during my recent refactoring (sigh).
**1.**
```
libaudit.c: In function 'audit_add_watch_dir':
libaudit.c:805:17: warning: pointer 'rule_19' may be used after 'realloc' [-Wuse-after-free]
805 |                 free(rule);
|                 ^~~~~~~~~~
libaudit.c:803:18: note: call to 'realloc' here
803 |         *rulep = realloc(rule, len + sizeof(*rule));
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
**2.**
```
libaudit.c: In function 'audit_rule_fieldpair_data':
libaudit.c:1839:33: warning: pointer 'rule_335' may be used after 'realloc' [-Wuse-after-free]
1839 | …
```
=> Fix compiler warnings

common/common.c, common/common.h, src/auditd-event.c
The space left action no longer supports HALT. If we reach this stage, ensure that all logged-in users are notified in case `admin_space_left_action` or `disk_space_full_action` is set to halt the system.
=> Broadcast a warning if a system halt is possible

audisp/plugins/remote/audisp-remote.c
[audisp-remote.c:stop_sock](https://github.com/linux-audit/audit-userspace/blob/v4.0.3/audisp/plugins/remote/audisp-remote.c#L1058) lacked NULL pointer checks if build configuration is with `--enable-gssapi-krb5=yes`.
If auditd is started with audisp-remote plugin active and `transport=KRB5`, the audisp-remote child crashes on connection errors with segfault in [krb5_cc_close](https://github.com/krb5/krb5/blob/e2e5f386ccf2bea1fa55ce544f43098ae2b38f89/src/lib/krb5/ccache/ccfns.c#L74) due to NULL pointer dereference. This will happen immediately at startup if the remote server is not available, or later if an already established connection breaks.
It may have been exploited as follows: auditd supervises the audisp-remote child. If it sees repeated crashes, it'll report "audisp-remote has …
=> Fix audisp-remote segfault on connection error

auparse/test/auparse_test.ref, auparse/test/auparse_test.ref.py, auparse/test/test.log, auparse/test/test2.log
Executing make check, the test case expected the system to have user gdm with id of 42, which might not be true in all cases. In case the user was not present, id-to-name translation failed, thus make check exited with error.
=> test suite: replace auid=42 with auid=0

init.d/auditd.condrestart
This is basically a follow up to yesterday's commit 483b03b88686c9c2088d3117394046d8d6ac3917 ("Remove awk dependency"). That commit was equivalent to a recent change in Fedora's audit package.
So another trivial but BRAVELY UNTESTED pull request.
=> Remove awk call in condrestart legacy script

configure.ac
I came across the following error when run `autoreconf -i --install`.
```
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'. libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am. configure.ac:42: installing './compile'
configure.ac:41: installing './missing'
Makefile.am: error: required file './README' not found audisp/Makefile.am: installing './depcomp'
bindings/swig/src/Makefile.am:25: warning: variable 'SWIG_SOURCES' is defined but no program or …
```
=> Add foreign option to automake

src/auditd.c
When the environment lacks libgcc_s.so.1, the program will abort when using the pthread_cancel function.
When executing auditd -s enable, the parent process will hang at the become_daemon function waiting for the child process to write to init_pipe[1]. The child process calls shutdown_events at line 972 in auditd.c, which in turn calls pthread_cancel. Due to the absence of libgcc_s.so.1 in the environment, the child process is terminated here, and the parent process continues to wait because it did not receive the write to init_pipe[1] from the child process, causing the program to hang.
Therefore, before calling shutdown_events, the parent process should be notified that it has already failed to ensure the parent process exits promptly.
=> Fix auditd -s enable hang issue (#457)

Makefile.am, audisp/Makefile.am, audisp/plugins/af_unix/Makefile.am, audisp/plugins/af_unix/audisp-af_unix.c, audisp/plugins/filter/Makefile.am, audisp/plugins/filter/audisp-filter.c, audisp/plugins/ids/ids.c, audisp/plugins/ids/timer-services.c, audisp/plugins/ids/timer-services.h, audisp/plugins/remote/Makefile.am, audisp/plugins/statsd/Makefile.am, audisp/plugins/statsd/audisp-statsd.c, audisp/queue.c, audisp/queue.h, audisp/test/Makefile.am, audisp/test/test-queue.c, auplugin/Makefile.am, auplugin/auplugin.c, auplugin/auplugin.h, auplugin/test/Makefile.am, auplugin/test/metrics_test.c, common/common.h, configure.ac, docs/Makefile.am, docs/auditd-plugins.5, docs/auplugin.3, src/auditd-event.c
Auplugin is intended to provide scaffolding most plugins need. It creates a worker thread, takes over main and places a lockless queue in between. This allows  plugins to adhere to best practices with minimal effort.
This is still a work in progess, but is functional. Merging now to avoid future conflicts as work lands in master.
=> Flesh out Auplugin

src/ausearch-report.c
Embedded fields, e.g. from libselinux in AVC records, are currently not correctly identified due to the name having trailing whitespaces. This leads to security contexts with MCS categories to be split, e.g.:
from
time->Fri Jun 13 23:26:09 2025
type=PROCTITLE msg=audit(1749849969.631:6691): proctitle=2F7573722F62696E2F706870002D66002F7661722F7777772F73697465732F6E657874636C6F75642F63726F6E2E706870
type=SYSCALL msg=audit(1749849969.631:6691): arch=c000003e syscall=64 success=no exit=-13 a0=7ea a1=3 a2=3b6 a3=7d6a32a17460 items=0 ppid=1 pid=200718 auid=4294967295 uid=33 gid=33 euid=33 suid=33 fsuid=33 egid=33 sgid=33 fsgid=33 tty=(none) ses=4294967295 comm="php" exe="/usr/bin/php8.4" subj=system_u:system_r:nextcloudcron_t:s0:c123,c456 key=(null)
type=AVC msg=audit(1749849969.631:6691): avc: …
=> interpret: correctly identify embedded fields

audisp/audispd-pconfig.c, audisp/audispd-pconfig.h, audisp/audispd.c
auditd: support loading plugin configs from symlinks
`auditd` previously did not support loading plugin configurations from
symlinked config files. This is problematic on systems such as NixOS,
which constructs basically the entirety of /etc using symlinks.
I considered why symlinks were not supported, and concluded the reason was
simplicity. While having a symlink point to a writable location would be
insecure, a user putting an insecure symlink to trigger this behavior could
also immediately do worse things.
There also were edge cases if the config file is replaced between the file
type check and the actual read. This is because `load_plugin_conf` uses
path based logic to check whether a file is a regular file or not, and then
asses the file path to `load_pconfig`. This means audispd …
=> auditd: support loading plugin configs from symlinks

auparse/auparse.h, lib/audit_logging.h, lib/libaudit.h
`sys/types.h` is indirectly included with `glibc`, but needs to be specified explicitly on musl.
~~The symbol collisions on `__attr_dealloc_free` require including auparse first for some reason.~~
Not a symbol collision, rather some `#define`s don't actually define `__attr_dealloc_free` causing the `#ifndef` to skip over `__attr_dealloc_free`, which is then all kinds of broken.
closes #475
=> fix build with musl

audisp/audispd.c
Fix inconsistent error handling in child process after fork() where the code was incorrectly (pointlessly?) setting conf->pid and using return -1 instead of exit(1). Child processes should exit immediately on error rather than attempting to return to the parent.
Also fix memory leak by freeing argv before exit when execve() fails.
=> Fix child process error handling and memory leak in safe_exec

auparse/interpret.c, auparse/nvlist.c
Hi, we are fuzzing auparse code and we found a potential segfault in `auparse_interp_adjust_type()`.
To reproduce that, used code:
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <locale.h>
#include <errno.h>
#include "libaudit.h"
#include "auparse.h"
unsigned int walked_fields = 0;
#define FIELDS_EXPECTED 403
static void walk_test(auparse_state_t *au)
{
int event_cnt = 1, record_cnt;
do {
if (auparse_first_record(au) <= 0) {
printf("Error getting first record (%s)\n",
strerror(errno));
exit(1);
}
printf("event %d has %u records\n", event_cnt,
auparse_get_num_records(au));
record_cnt = 1;
do {
printf("    record %d of type %d(%s) has %u fields\n",
record_cnt,
auparse_get_type(au),
audit_msg_type_to_name(auparse_get_type(au)), …
```
=> Fix possible deference crash in auparse_interp_adjust_type()

lib/libaudit.c
with glibc, `basename` is provided by string.h. However, musl exposes `basename` only in `libgen.h`.
In glibc `libgen.h`, there is this warning:
```C
/* Return final component of PATH.
This is the weird XPG version of this function.  It sometimes will
modify its argument.  Therefore we normally use the GNU version (in
<string.h>) and only if this header is included make the XPG
version available under the real name.  */
extern char *__xpg_basename (char *__path) __THROW;
#define basename	__xpg_basename
```
This makes that version of `basename` probably a bad default. As far as i can tell, this is not an issue on musl. Hence, only fall back to `libgen.h` if `basename` is not yet defined.
=> libaudit: fix includes for musl once again
